---

<h1 align=left><font size = 8, style="color:rgb(200,0,0)"><b>Bibliotecas: <br>
- Numpy
</b></font></h1>

---

# Numpy
[Numpy](https://numpy.org/)

## Importando a biblioteca

In [ ]:
import numpy as np

## Criar arranjos de números

In [ ]:
idades = np.array([10, 15, 20, 18])
notas = np.array([9,8,5,7])

## Imprimindo os dados

In [ ]:
idades

array([10, 15, 20, 18])

In [ ]:
print(idades)

[10 15 20 18]


## Imprimir o tipo do dado

In [ ]:
type(idades)

numpy.ndarray

In [ ]:
type(12)

int

## Imprimindo os dados que cumpram uma condição

In [ ]:
print(notas[idades==20])

[5]


## Média

In [ ]:
np.mean(idades)

15.75

In [ ]:
np.mean(notas)

7.25

## Criando arranjo de dados (matrizes)

In [ ]:
salario = np.array([ [1000, 1200, 1300],
                    [800, 900, 950 ],
                    [2000, 2100, 2200] ])

In [ ]:
salario

array([[1000, 1200, 1300],
       [ 800,  900,  950],
       [2000, 2100, 2200]])

## Localizando celulas

In [ ]:
salario[1, 2]

950

In [ ]:
salario[0, 2]

1300

- se queremos conhecer os dados da linha `0` e coluna `2`

In [ ]:
salario[0,2]

- **praticando** <br> obtenha a sub-matriz de 2x2

In [ ]:
salario[:2,:2]

array([[1000, 1200],
       [ 800,  900]])

- **praticando** <br>
Obtenha a sub-matriz 900, 950 e 2100, 2200m

In [ ]:
salario[1:3, 1:3 ]

array([[ 900,  950],
       [2100, 2200]])

- **praticando** <br> Obtenha a sub-matriz 1200, 1300 e 900, 950 e 2100, 2200

In [ ]:
salario[:, 1:]

array([[1200, 1300],
       [ 900,  950],
       [2100, 2200]])

## Funções trigonometricas

In [ ]:
np.cos(1)

0.5403023058681398

## Criar listas ou arranjos com valores

> matriz 4 x 3 de zeros

In [ ]:
matriz = np.zeros([4,3])
matriz

> matriz 3 x 3 de Zeros

In [ ]:
matriz = np.zeros([3,3])
matriz

## Criar arranjos utilizando o loop FOR


In [ ]:

for i in range(0, 3):
    for j in range(0, 3):
        matriz[i][j] = 1

matriz

- Matriz contendo valores de 1

In [ ]:
matriz2 = np.ones([3, 2])
matriz2