---

<h1 align=left><font size = 8, style="color:rgb(200,0,0)"><b>Bibliotecas: <br>
- Numpy <br>
- Pandas
</b></font></h1>

---


### **Lista de Exercícios: Utilização de NumPy e Pandas no Google Colab**




#### **1. Exercícios com NumPy**



1. **Criação de Arrays:**
   - Crie um array unidimensional com os números de 0 a 9. Em seguida, crie um array bidimensional (matriz) de 3x3 com números aleatórios entre 1 e 10.


In [1]:
import numpy as np

# Criação de um array unidimensional com os números de 0 a 9
array_unidimensional = np.arange(10)

# Criação de um array bidimensional (matriz) 3x3 com números aleatórios entre 1 e 10
array_bidimensional = np.random.randint(1, 11, size=(3, 3))

print(array_unidimensional)
print(array_bidimensional)


[0 1 2 3 4 5 6 7 8 9]
[[7 5 8]
 [1 8 8]
 [2 2 6]]



2. **Operações Básicas com Arrays:**
   - Crie dois arrays de tamanho 5 com números inteiros. Realize operações básicas como adição, subtração e multiplicação entre eles.



In [2]:
import numpy as np

# Criação de dois arrays de tamanho 5 com números inteiros aleatórios
array1 = np.random.randint(1, 20, size=5)
array2 = np.random.randint(1, 20, size=5)

# Operações básicas: adição, subtração e multiplicação entre os arrays
soma = array1 + array2
subtracao = array1 - array2
multiplicacao = array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Adição:", soma)
print("Subtração:", subtracao)
print("Multiplicação:", multiplicacao)


Array 1: [13  8 19  3 16]
Array 2: [19  4 17  6 14]
Adição: [32 12 36  9 30]
Subtração: [-6  4  2 -3  2]
Multiplicação: [247  32 323  18 224]



3. **Estatísticas Básicas:**
   - Dado um array de números aleatórios de tamanho 100, calcule a média, mediana e desvio padrão.


In [3]:
import numpy as np

# Criação de um array de números aleatórios de tamanho 100
array_estatisticas = np.random.randint(1, 101, size=100)

# Cálculo da média, mediana e desvio padrão
media = np.mean(array_estatisticas)
mediana = np.median(array_estatisticas)
desvio_padrao = np.std(array_estatisticas)

print("Array:", array_estatisticas)
print("Média:", media)
print("Mediana:", mediana)
print("Desvio Padrão:", desvio_padrao)


Array: [100  15  30  41  26  83  50  75  49  17  88  91  52  37  57  69  41  69
  61  44  29  91  51  44  34  73  48  22  42  49  23  57   3  90  79  19
  12  57  52  60 100  41  77  12  97  36  90  57  17  98  99  38  84  46
  96  91  74  27  46  84  52  36  16  37  57  10  82  99  47  88  22  66
  82  34  87  33  67   8  49  21  24  35  37  93   9  36  93   7   2  57
  33  57   1  28  64  73  24  83  79  28]
Média: 51.96
Mediana: 49.0
Desvio Padrão: 27.945275092580502




4. **Indexação e Fatiamento:**
   - Crie um array de 1 a 20 e selecione os elementos nas posições pares. Em seguida, selecione os elementos maiores que 10.



In [4]:
import numpy as np

# Criação de um array de 1 a 20
array_indexacao = np.arange(1, 21)

# Seleção dos elementos nas posições pares (índices ímpares)
elementos_pares = array_indexacao[1::2]

# Seleção dos elementos maiores que 10
elementos_maiores_que_10 = array_indexacao[array_indexacao > 10]

print("Array:", array_indexacao)
print("Elementos nas posições pares:", elementos_pares)
print("Elementos maiores que 10:", elementos_maiores_que_10)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Elementos nas posições pares: [ 2  4  6  8 10 12 14 16 18 20]
Elementos maiores que 10: [11 12 13 14 15 16 17 18 19 20]



5. **Reshape e Transposição:**
   - Crie um array de 12 elementos e reshaping-o para uma matriz de 3x4. Em seguida, transponha a matriz.



In [5]:
import numpy as np

# Criação de um array de 12 elementos
array_reshape = np.arange(12)

# Reshape do array para uma matriz de 3x4
matriz_3x4 = array_reshape.reshape(3, 4)

# Transposição da matriz
matriz_transposta = matriz_3x4.T

print("Array:", array_reshape)
print("Matriz 3x4:", matriz_3x4)
print("Matriz transposta:", matriz_transposta)


Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz 3x4: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Matriz transposta: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]



#### **2. Exercícios com Pandas**



6. **Criação de DataFrame:**
   - Crie um DataFrame com as seguintes colunas: `Nome`, `Idade`, e `Cidade`, e adicione alguns dados fictícios.



7. **Leitura e Escrita de Arquivos CSV:**
   - Crie um DataFrame com alguns dados e salve-o em um arquivo CSV. Em seguida, leia o arquivo CSV e exiba o conteúdo.




8. **Manipulação de Dados:**
   - Adicione uma nova coluna ao DataFrame com valores calculados, como a idade em meses (suponha que cada ano tem 12 meses).




9. **Filtragem de Dados:**
   - Filtre o DataFrame para mostrar apenas as linhas onde a idade é maior que 30.




10. **Estatísticas Descritivas:**
    - Utilize o DataFrame criado para calcular a média e o desvio padrão da coluna `Idade`.
